---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: production
  labels:
    app: cartservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    # cart-sa → IAM Role cho phép đọc ElastiCache endpoint
    # từ AWS Secrets Manager prod/cart/*
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
