images:
  repository: 492462084314.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique
  tag: "latest"

frontend:
  create: true
  name: frontend
  externalService: true
  platform: local
  cymbalBranding: false
  singleSharedSession: false
  virtualService:
    create: false
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false

serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true

loadGenerator:
  create: false

opentelemetryCollector:
  create: false

googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false

securityContext:
  enable: true

seccompProfile:
  enable: true
  type: RuntimeDefault
