images:
  repository: 492462084314.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique
  tag: "latest"

frontend:
  create: true
  name: frontend
  externalService: true
  platform: local
  cymbalBranding: false
  singleSharedSession: false
  virtualService:
    create: false
  resources:
    requests:
      cpu: 150m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi

networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false

serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true

loadGenerator:
  create: false
opentelemetryCollector:
  create: false

googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false

securityContext:
  enable: true

seccompProfile:
  enable: true
  type: RuntimeDefault

adService:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 400m
      memory: 400Mi

cartService:
  resources:
    requests:
      cpu: 200m
      memory: 150Mi
    limits:
      cpu: 400m
      memory: 300Mi

checkoutService:
  resources:
    requests:
      cpu: 150m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi

currencyService:
  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 300Mi

emailService:
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 192Mi

paymentService:
  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 300Mi

productCatalogService:
  resources:
    requests:
      cpu: 150m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi

recommendationService:
  resources:
    requests:
      cpu: 150m
      memory: 250Mi
    limits:
      cpu: 300m
      memory: 500Mi

shippingService:
  resources:
    requests:
      cpu: 150m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi
