# ============================================================
#   Tạo service account tương ứng bên trong cluster eks
# ============================================================

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: production
  labels:
    app: frontend
    standard: "CIS-EKS-5.1.1"
automountServiceAccountToken: false # Không mount token mặc định
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: production
  labels:
    app: productcatalogservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: production
  labels:
    app: cartservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: production
  labels:
    app: checkoutservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: production
  labels:
    app: paymentservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-sa
  namespace: production
  labels:
    app: shippingservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-sa
  namespace: production
  labels:
    app: emailservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice-sa
  namespace: production
  labels:
    app: recommendationservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice-sa
  namespace: production
  labels:
    app: adservice
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice-sa
  namespace: production
  labels:
    app: currencyservice
automountServiceAccountToken: false
