---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-sa
  namespace: production
  labels:
    app: emailservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    # email-sa → IAM Role có quyền ses:SendEmail
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
