---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-sa
  namespace: production
  labels:
    app: shippingservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
