---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice-sa
  namespace: production
  labels:
    app: adservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    # adservice-sa → IAM Role có quyền cloudwatch:PutMetricData
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
