---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: production
  labels:
    app: paymentservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    # payment-sa → IAM Role có quyền đọc prod/payment/* trong Secrets Manager
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
