---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice-sa
  namespace: production
  labels:
    app: currencyservice
    app.kubernetes.io/part-of: online-boutique
  annotations:
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
