apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: production
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: online-boutique
  annotations:
    eks.amazonaws.com/pod-identity-association: "true"
automountServiceAccountToken: false
